apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-03-22T12:54:58Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "37"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 39f90d33-2dd0-11e8-84c3-0800277410ef
spec:
  clusterIP: 20.32.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
