apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alert-pv
  labels:
    app: prometheus-alert
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-server.example.com
    path: /home/nfsshare/prometheus-alertmng
  storageClassName: 
